### ISSUE TITLE
Prepare cpunks for pypi with packaging

### ISSUE THREAD

**Issue by jmsdnns** [tnn1t1s/cpunks-10k#11]
We'd like cpunks to go on pypi. We'd also like it to include some things that make experimentation easier for new users.

A design that could work for this is to package everything under `cpunks/`, including jupyter notebooks or pickled data, and write code in `setup.py` that knows how to include them in the distributions for this library.

It might be the case that having a CLI makes it significantly easier to do things using the packaged data.

**Comment by jmsdnns** [comment]
Relevant PR #12

**Comment by tnn1t1s** [comment]
merged after testing. will create followup issue for docs.
