### ISSUE TITLE
Numpy Funpy

### ISSUE THREAD

**Issue by tnn1t1s** [tnn1t1s/cpunks-10k#2]
Given an input array, np.array([[0, 1, 2],[1, 2, 0], [2, 0, 1]]), of shape (3,3),
and an overlay array, np.array([[1, 2],[3, 4]]) of shape, 2,2, compute the

desired_output = np.array([
                           [1, 2, 1, 2, 1, 2],
                           [3, 4, 3, 4, 3, 4],
                           [1, 2, 1, 2, 1, 2],
                           [3, 4, 3, 4, 3, 4],
                           [1, 2, 1, 2, 1, 2],
                           [3, 4, 3, 4, 3, 4],
                           ] )

obtained by substituting the overlay array for each cell in the input array to create a new image that looks to be composed of tiles of the overlay array.

**Comment by tnn1t1s** [comment]
plt.imshow(square)
![image](https://user-images.githubusercontent.com/3397401/150018386-d2f0beee-0219-415e-bf27-89756e4ea6e2.png)

**Comment by tnn1t1s** [comment]
plt.imshow(overlay)

![image](https://user-images.githubusercontent.com/3397401/150018549-d45a8f8a-2ba7-4d30-8bf9-38ae9c501cd1.png)

**Comment by tnn1t1s** [comment]
plt.imshow(desired_output)

![image](https://user-images.githubusercontent.com/3397401/150018666-91ad7e4b-f91f-4af0-836a-c0a24cc9ffa7.png)

**Comment by tnn1t1s** [comment]
another example that demonstrates the overlay 

square = np.array([[1, 2, 0],[1, 2, 0], [1, 2, 0]])
overlay= {}
overlay[1] = np.array([[0, 1],[2, 3]])
overlay[2] = np.array([[4, 5],[6, 7]])
overlay[3] = np.array([[8, 9],[0, 1]])

desired_output = np.array([
                           [0, 1, 4, 5, 8, 9],
                           [2, 3, 6, 7, 0, 1],
                           [0, 1, 4, 5, 8, 9],
                           [2, 3, 6, 7, 0, 1],
                           [0, 1, 4, 5, 8, 9],
                           [2, 3, 6, 7, 0, 1],
                           ] )

**Comment by tnn1t1s** [comment]
https://towardsdatascience.com/advanced-numpy-master-stride-tricks-with-25-illustrated-exercises-923a9393ab20

**Comment by jmsdnns** [comment]
Here is a solution that uses for loops and a lambda. Using `np.block` allowed the solution to look simple in code, once the two for loops have done most of the work.

```python
def bloc_party(input_arr, selector):
    return np.block([[selector(i) for i in j] for j in input_arr])
```

`input_arr` maps to `input_arr` and `square` in the two problems and is used to determine the size of the structure created.

`selector` is a function that can either return the overlay array as it is, or can retrieve a particular overlay array if you have more than one.

# First Problem

The first problem has a single overlay array, so it's selector is: `lambda i: overlay_arr`

```python
>>> input_arr = np.array([
...     [0, 1, 2],
...     [1, 2, 0],
...     [2, 0, 1]])
>>> 
>>> overlay_arr = np.array([
...     [1, 2],
...     [3, 4]])
>>> 
>>> # The selector function simply returns overlay_arr
>>> bloc_party(input_arr, lambda i: overlay_arr)
array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])
```

# Second Problem

The second problem has a multiple overlay arraya, so it's selector uses the values from square as the index for look up in the overlay dict: `lambda i: overlay[i]`

```python
>>> square = np.array([
...     [1, 2, 0],
...     [1, 2, 0],
...     [1, 2, 0]
... ])
>>> 
>>> overlay = {}
>>> overlay[1] = np.array([
...     [0, 1],
...     [2, 3]])
>>> overlay[2] = np.array([
...     [4, 5],
...     [6, 7]])
>>> overlay[0] = np.array([
...     [8, 9],
...     [0, 1]])
>>> 
>>> 
>>> bloc_party(square, lambda i: overlay[i])
array([[0, 1, 4, 5, 8, 9],
       [2, 3, 6, 7, 0, 1],
       [0, 1, 4, 5, 8, 9],
       [2, 3, 6, 7, 0, 1],
       [0, 1, 4, 5, 8, 9],
       [2, 3, 6, 7, 0, 1]])
```

**Comment by tnn1t1s** [comment]
this is great. check out this example of overlaying images from the commodore PETSCII 8 bit character sets on a 3*3 image ...

`square = np.array([[83, 2, 0],[1, 2, 0], [1, 2, 0]])
all_hash = np.array([[163, 163, 163],[163, 163, 163], [163, 163, 163]])
a = bloc_party(all_hash, lambda i: PETS_GRAY[i])
a = bloc_party(square, lambda i: PETS_GRAY[i])

fig = plt.figure(figsize=(4,8))
fig.add_subplot(1,2, 1)
plt.imshow(bloc_party(all_hash, lambda i: PETS_GRAY[i]), cmap=cmap)
fig.add_subplot(1,2, 2)
plt.imshow(bloc_party(square, lambda i: PETS_GRAY[i]), cmap=cmap)`

**Comment by tnn1t1s** [comment]
![image](https://user-images.githubusercontent.com/3397401/150144237-f691e72e-facf-43f3-aee9-da4941692da8.png)

**Comment by tnn1t1s** [comment]
to get PETS_ ...

```
def get_tile_images(image, width=8, height=8):
    _nrows, _ncols, depth = image.shape
    _size = image.size
    _strides = image.strides

    nrows, _m = divmod(_nrows, height)
    ncols, _n = divmod(_ncols, width)
    if _m != 0 or _n != 0:
        return None

    return np.lib.stride_tricks.as_strided(
        np.ravel(image),
        shape=(nrows, ncols, height, width, depth),
        strides=(height * _strides[0], width * _strides[1], *_strides),
        writeable=False
    )

def rgb2gray(rgb):
    weights = [0.2989, 0.5870, 0.1140]
    return np.dot(rgb[...,:3], weights)
```

then ...

```
import matplotlib.image as mpimg
petscii = mpimg.imread(f"./images/petscii.png")
PETS_ = get_tile_images(petscii, width=8, height=8)
PETS_  = PETS_.reshape(280,8,8,4)#.astype(np.uint8)
cmap = plt.get_cmap('gray')

PETS_GRAY = np.array([rgb2gray(img) for img in PETS_])
#PETS_  = PETS_.reshape(280,8,8,4)#.astype(np.uint8)
#plt.imshow(PETS_[163])
#PETS_[163].shape
plt.imshow(PETS_GRAY[163], cmap=cmap)
```

**Comment by tnn1t1s** [comment]
![image](https://user-images.githubusercontent.com/3397401/150150703-416b0b0b-4548-4b29-8a44-2c78c20b13ea.png)

**Comment by tnn1t1s** [comment]
cryptoPETS

![image](https://user-images.githubusercontent.com/3397401/150179950-d83c8431-dcc2-4435-8f44-85ee1f9cbe04.png)

**Comment by jmsdnns** [comment]
![index](https://user-images.githubusercontent.com/7950614/150182789-e4f5adef-fc1b-47e4-b93c-1c66c0ec3890.png)

**Comment by jmsdnns** [comment]
![m](https://user-images.githubusercontent.com/7950614/150183465-5b447b69-04db-4c5e-ac78-47c2654a569b.png)
🤘

**Comment by tnn1t1s** [comment]
![image](https://user-images.githubusercontent.com/3397401/150240262-f2d87a7f-43e9-4826-a575-a6accde5a918.png)

**Comment by tnn1t1s** [comment]
did it *learn* the eyes ????

**Comment by tnn1t1s** [comment]
![image](https://user-images.githubusercontent.com/3397401/150243201-c72c59c7-6eeb-4998-a2ff-7cf7ce8f9190.png)

**Comment by tnn1t1s** [comment]
![image](https://user-images.githubusercontent.com/3397401/150243381-5ed9310b-8de1-48de-b099-d22d0c07345f.png)

**Comment by tnn1t1s** [comment]
![image](https://user-images.githubusercontent.com/3397401/150243870-342075d6-c252-4343-86dc-ac3d05898651.png)
